#!/usr/bin/env bash
# catalog-endpoints.sh — scan an unpacked tree for endpoints and write markdown.
# Does not patch files.
# Usage: bash catalog-endpoints.sh --dir apktool_out --out docs/endpoints.md

set -euo pipefail

DIR=""
OUT=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dir) DIR="$2"; shift 2 ;;
    --out) OUT="$2"; shift 2 ;;
    --help)
      echo "Usage: catalog-endpoints.sh --dir UNPACKED --out endpoints.md"
      exit 0
      ;;
    *) echo "Unknown: $1" >&2; exit 1 ;;
  esac
done

if [[ -z "$DIR" || ! -d "$DIR" ]]; then
  echo "Need --dir pointing at an unpacked tree" >&2
  exit 1
fi
if [[ -z "$OUT" ]]; then
  echo "Need --out markdown path" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUT")"
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

# Text-ish files only. Skip common binary bundles so the inventory stays readable.
find "$DIR" -type f \
  ! -name '*.so' ! -name '*.dex' ! -name '*.png' ! -name '*.jpg' \
  ! -name '*.webp' ! -name '*.ogg' ! -name '*.mp3' ! -name '*.bundle' \
  -print0 2>/dev/null |
  xargs -0 grep -I -n -E -o -h \
    'https?://[^[:space:]"'"'"'<>]+|wss?://[^[:space:]"'"'"'<>]+|[A-Za-z0-9.-]+\.[A-Za-z]{2,}:[0-9]{2,5}' \
    2>/dev/null |
  sed 's/[[:space:]]*$//' |
  sort -u > "$TMP" || true

{
  echo "# Endpoints"
  echo
  echo "Generated by \`catalog-endpoints.sh\`. Fill role, protocol, and replacement. The script does not patch."
  echo
  echo "Target may be an IPv4, an IPv6, or a domain. Gateway and update must both be filled before redirect is done."
  echo
  echo "| Role | Official | Scheme | Host | Port | Protocol | Replacement | Evidence |"
  echo "|------|----------|--------|------|------|----------|-------------|----------|"
  echo "| update | | | | | | | |"
  echo "| cdn | | | | | | | |"
  echo "| gateway | | | | | | | |"
  echo "| login | | | | | | | |"
  echo "| zone | | | | | | | |"
  echo "| game | | | | | | | |"
  echo "| notice | | | | | | | |"
  echo "| config | | | | | | | |"
  echo
  echo "## Raw hits"
  echo
  echo '```'
  if [[ -s "$TMP" ]]; then
    head -200 "$TMP"
  else
    echo "(no URL or host:port hits)"
  fi
  echo '```'
} > "$OUT"

COUNT=$(wc -l < "$TMP" | tr -d ' ')
echo "{\"out\":\"$OUT\",\"raw_hits\":$COUNT}"
