#!/usr/bin/env bash
# catalog-client.sh — index likely master-data files and create empty section docs.
# Does not parse table schemas. Fill IDs by hand from dump.cs and the indexed files.
# Matches English and a few pinyin stems. Chinese characters in filenames are not
# matched; add those paths to docs/index.md by hand.
# Usage: bash catalog-client.sh --dir apktool_out --out cases/<slug>/docs

set -euo pipefail

DIR=""
OUT=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dir) DIR="$2"; shift 2 ;;
    --out) OUT="$2"; shift 2 ;;
    --help)
      echo "Usage: catalog-client.sh --dir UNPACKED --out docs_dir"
      exit 0
      ;;
    *) echo "Unknown: $1" >&2; exit 1 ;;
  esac
done

if [[ -z "$DIR" || ! -d "$DIR" ]]; then
  echo "Need --dir pointing at an unpacked tree" >&2
  exit 1
fi
if [[ -z "$OUT" ]]; then
  echo "Need --out docs directory" >&2
  exit 1
fi

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
ROOT=$(cd "$SCRIPT_DIR/.." && pwd)
TEMPLATE_DIR="$ROOT/templates/docs"

mkdir -p "$OUT/master-data"

classify() {
  local base
  base=$(basename "$1" | tr '[:upper:]' '[:lower:]')
  case "$base" in
    *monster*|*enemy*|*npc*|*guaiwu*) echo "monsters" ;;
    *hero*|*character*|*role*|*player*|*juese*) echo "characters" ;;
    *map*|*scene*|*stage*|*dungeon*|*ditu*) echo "maps" ;;
    *activity*|*event*|*huodong*) echo "activities" ;;
    *item*|*equip*|*goods*) echo "items" ;;
    *skill*|*spell*) echo "skills" ;;
    *quest*|*mission*) echo "quests" ;;
    *drop*|*reward*) echo "drops" ;;
    *) echo "" ;;
  esac
}

format_of() {
  local base
  base=$(basename "$1" | tr '[:upper:]' '[:lower:]')
  case "$base" in
    *.json) echo "JSON" ;;
    *.csv|*.tsv) echo "CSV" ;;
    *.xml) echo "XML" ;;
    *.lua) echo "Lua" ;;
    *.txt) echo "text" ;;
    *.bytes|*.bin|*.dat) echo "binary blob" ;;
    *.bundle|*.assets) echo "AssetBundle" ;;
    *.msgpack) echo "MessagePack" ;;
    *) echo "unknown" ;;
  esac
}

INDEX="$OUT/index.md"
{
  echo "# Client catalog index"
  echo
  echo "Generated by \`catalog-client.sh\`. Row count stays \`unparsed\` until you open the file."
  echo "English and pinyin stems are indexed. Filenames that contain Chinese characters are not; add those paths here by hand."
  echo "Fill \`docs/master-data/\` from these paths and from \`dump.cs\`. Do not invent IDs."
  echo
  echo "| Section | Source | Format | Row count |"
  echo "|---------|--------|--------|-----------|"
} > "$INDEX"

HITS=0
while IFS= read -r path; do
  [[ -z "$path" ]] && continue
  section=$(classify "$path")
  [[ -z "$section" ]] && continue
  rel=${path#"$DIR"/}
  fmt=$(format_of "$path")
  echo "| $section | \`$rel\` | $fmt | unparsed |" >> "$INDEX"
  HITS=$((HITS + 1))
done < <(find "$DIR" -type f 2>/dev/null | sort)

if [[ "$HITS" -eq 0 ]]; then
  echo "| (none) | | | |" >> "$INDEX"
fi

for name in characters monsters maps activities items skills quests; do
  dest="$OUT/master-data/$name.md"
  if [[ ! -f "$dest" ]]; then
    cp "$TEMPLATE_DIR/master-data/$name.md" "$dest"
  fi
done

if [[ ! -f "$OUT/boot-sequence.md" ]]; then
  cp "$TEMPLATE_DIR/boot-sequence.md" "$OUT/boot-sequence.md"
fi

echo "{\"out\":\"$OUT\",\"indexed_files\":$HITS}"
